apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    tier: front
  name: vote
spec:
  selector:
    matchLabels:
      app: vote
  template:
    spec:
      containers:
      - name: vote
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        envFrom: 
          - configMapRef: 
              name: vote-options
              optional: true



