apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 2
images:
- name: schoolofdevops/vote
  newName: dopsdemo/vote
  newTag: main-7c20e93c-1619242117 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
