apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v2
        name: vote
        resources:
          limits:
            cpu: 200Mi
            memory: 500m
          requests:
            cpu: 200Mi
            memory: 200m

